[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.5.2"

[dependencies]
httparse = "1.1.2"
log = "0.3.6"
rand = "0.3.14"
sha1 = "0.2.0"
url = "1.2.0"
# Warning! Using dev branch (we need https://github.com/carllerche/mio/pull/444 for windows support)
mio = { git = "https://github.com/wdv4758h/mio", rev = "1c4b62d6e82b5b9904856063b421bb0f6c031f04" }
slab = { git = "https://github.com/carllerche/slab", rev = "5476efcafb"}
bytes = { git = "https://github.com/carllerche/bytes" }

[dependencies.libc]
optional = true
version = "0.2.15"

[dependencies.libz-sys]
optional = true
version = "1.0.5"

[dependencies.openssl]
optional = true
version = "0.7.14"

[dev-dependencies]
clap = "2.10.0"
env_logger = "0.3.4"
term = "0.4.4"
time = "0.1.35"

[features]
default = []
permessage-deflate = ["libz-sys", "libc"]
ssl = ["openssl"]
